# Week 2 Summary
> NAME: $\color{red}{\text{Lucien Chen}}$
> 
> PID: $\color{red}{\text{A17004542}}$
>
> 
---

I certify that the following write-up is my own work, and have abided by the UCSD Academic Integrity Guidelines.

- [x] Yes
- [ ] No

% # %load tex-macros
<div hidden>
\newcommand{\require}[1]{}
$\usepackage{amsmath}$
$\require{begingroup}\require{newcommand}$
$\long\def \forcecommand #1{\providecommand{#1}{}\renewcommand{#1}}$
$\forcecommand{\defeq}{\stackrel{\small\bullet}{=}}$
$\forcecommand{\ra}{\rangle}$
$\forcecommand{\la}{\langle}$
$\forcecommand{\pr}{{\mathbb P}}$
$\forcecommand{\qr}{{\mathbb Q}}$
$\forcecommand{\xv}{{\boldsymbol{x}}}$
$\forcecommand{\av}{{\boldsymbol{a}}}$
$\forcecommand{\bv}{{\boldsymbol{b}}}$
$\forcecommand{\cv}{{\boldsymbol{c}}}$
$\forcecommand{\dv}{{\boldsymbol{d}}}$
$\forcecommand{\ev}{{\boldsymbol{e}}}$
$\forcecommand{\fv}{{\boldsymbol{f}}}$
$\forcecommand{\gv}{{\boldsymbol{g}}}$
$\forcecommand{\hv}{{\boldsymbol{h}}}$
$\forcecommand{\nv}{{\boldsymbol{n}}}$
$\forcecommand{\sv}{{\boldsymbol{s}}}$
$\forcecommand{\tv}{{\boldsymbol{t}}}$
$\forcecommand{\uv}{{\boldsymbol{u}}}$
$\forcecommand{\vv}{{\boldsymbol{v}}}$
$\forcecommand{\wv}{{\boldsymbol{w}}}$
$\forcecommand{\zerov}{{\mathbf{0}}}$
$\forcecommand{\onev}{{\mathbf{0}}}$
$\forcecommand{\phiv}{{\boldsymbol{\phi}}}$
$\forcecommand{\cc}{{\check{C}}}$
$\forcecommand{\xv}{{\boldsymbol{x}}}$
$\forcecommand{\Xv}{{\boldsymbol{X}\!}}$
$\forcecommand{\yv}{{\boldsymbol{y}}}$
$\forcecommand{\Yv}{{\boldsymbol{Y}}}$
$\forcecommand{\zv}{{\boldsymbol{z}}}$
$\forcecommand{\Zv}{{\boldsymbol{Z}}}$
$\forcecommand{\Iv}{{\boldsymbol{I}}}$
$\forcecommand{\Jv}{{\boldsymbol{J}}}$
$\forcecommand{\Cv}{{\boldsymbol{C}}}$
$\forcecommand{\Ev}{{\boldsymbol{E}}}$
$\forcecommand{\Fv}{{\boldsymbol{F}}}$
$\forcecommand{\Gv}{{\boldsymbol{G}}}$
$\forcecommand{\Hv}{{\boldsymbol{H}}}$
$\forcecommand{\alphav}{{\boldsymbol{\alpha}}}$
$\forcecommand{\epsilonv}{{\boldsymbol{\epsilon}}}$
$\forcecommand{\betav}{{\boldsymbol{\beta}}}$
$\forcecommand{\deltav}{{\boldsymbol{\delta}}}$
$\forcecommand{\gammav}{{\boldsymbol{\gamma}}}$
$\forcecommand{\etav}{{\boldsymbol{\eta}}}$
$\forcecommand{\piv}{{\boldsymbol{\pi}}}$
$\forcecommand{\thetav}{{\boldsymbol{\theta}}}$
$\forcecommand{\tauv}{{\boldsymbol{\tau}}}$
$\forcecommand{\muv}{{\boldsymbol{\mu}}}$
$%$
$\forcecommand{\sd}{\text{SD}}$
$\forcecommand{\se}{\text{SE}}$
$\forcecommand{\med}{\text{median}}$
$\forcecommand{\median}{\text{median}}$
$%$
$\forcecommand{\supp}{\text{supp}}$
$\forcecommand{\E}{\mathbb{E}}$
$\forcecommand{\var}{\text{Var}}$
$\forcecommand{\Ber}{{\text{Ber}}}$
$\forcecommand{\Bin}{{\text{Bin}}}$
$\forcecommand{\Geo}{{\text{Geo}}}$
$\forcecommand{\Unif}{{\text{Unif}}}$
$\forcecommand{\Poi}{{\text{Poi}}}$
$\forcecommand{\Exp}{{\text{Exp}}}$
$\forcecommand{\Chisq}{{\chi^2}}$
$\forcecommand{\N}{\mathbb{N}}$
$\forcecommand{\iid}{{\stackrel{iid}{\sim}}}$
$\forcecommand{\px}{p_{X}}$
$\forcecommand{\fx}{f_{X}}$
$\forcecommand{\Fx}{F_{X}}$
$\forcecommand{\py}{p_{Y}}$
$\forcecommand{\pxy}{p_{X,Y}}$
$\forcecommand{\po}{{p_0}}$
$\forcecommand{\pa}{{p_a}}$
$\forcecommand{\Xbar}{\overline{X}}$
$\forcecommand{\Ybar}{\overline{Y}}$
$\forcecommand{\Zbar}{\overline{Z}}$
$\forcecommand{\nXbar}{n \cdot \overline{X}}$
$\forcecommand{\nYbar}{n \cdot \overline{Y}}$
$\forcecommand{\nZbar}{n \cdot \overline{Z}}$
$\forcecommand{\Xn}{X_1, X_2, \dots, X_n}$
$\forcecommand{\Xm}{{X_1, X_2, \dots, X_m}}$
$\forcecommand{\Yn}{Y_1, Y_2, \dots, Y_n}$
$\forcecommand{\Ym}{{Y_1, Y_2, \dots, Y_m}}$
$\forcecommand{\sumXn}{X_1 + X_2 + \dots + X_n}$
$\forcecommand{\sumym}{Y_1 + Y_2 + \dots + Y_m}$
$\forcecommand{\la}{\ell_\alpha}$
$\forcecommand{\ua}{u_\alpha}$
$\forcecommand{\at}{{\alpha/2}}$
$\forcecommand{\mux}{\mu_{X}}$
$\forcecommand{\muy}{\mu_{Y}}$
$\forcecommand{\sx}{\sigma_{X}}$
$\forcecommand{\sy}{\sigma_{Y}}$
$\forcecommand{\ci}{\text{CI}}$
$\forcecommand{\pvalue}{$p$-value}$
$\forcecommand{\Ho}{H_{0}}$
$\forcecommand{\Ha}{H_{a}}$

\vskip-\parskip
\vskip-\baselineskip
</div>

In [1]:
import numpy as np
import scipy
from scipy import stats as stats

---

## Key Takeaways from Week 1


#### Tuesday: 

There are three different types of probability: empirical, theoretical and subjective. We discuss different types of probability functions: probability mass functions and probability density functions as well as the cumulative distribution functions. Several well known probability distributions covered in class include the Uniform, Exponential, Poisson, Normal, etc. They all have well known properties such as their expectations and variance. 

#### Thursday

We covered some theorems such as the law or large numbers and central limit theorem which tells us how statistics will act asymptotically. We also cover sampling distributions and the empirical distribution function which allows us to compute the quantiles of a sample. We then move on to confidence intervals which allow us to capture the true value of a proportion with $\alpha$ level of confidence. The two examples covered in class are confidence intervals for one sample proportions and for two sample difference in proportions.


---

## Tue, Apr 9th

#### Probability Review

Given a sample space $\mathcal{S}$ and an event $A$, there are three qualiatively different ways to define the probability $P(A)$:

**Empiricial Probability**


$$
P(A) = \frac{\# \text{ of times A occurs}}{\# \text{ of trials}}
$$

An example of empirical probability is the following scenario:

> Throwing a die 10 times and observing the number of 6's you get

**Theoretical Probability**


$$
P(A) = \frac{\# \text{ of ways A can occur}}{\# \text{ of possible outcomes}}
$$

An example of theoretical probability is the following scenario:

> When flipping a fair coin, the theoretical probability that we get tails is 0.5 (1 way to get Tails/2 possible outcomes)

**Subjective Probability**


$$
P(A) = \text{degree of belief that A will occur}
$$

#### Random Variables

Intuitively, a random variable $X$ is a variable whose value is the numerical outcome of a random phenomenon and, the support of a random variable, denoted $\text{supp}(X)$, is the set of values X can take sometimes denoted $x \in \{X_1, X_2,..., X_N\}$

The distribution of a random variable describes the probability of each outcome denoted by $X \sim f(\theta)$ for some parameter of interest $\theta$.

For example:

$$ X \sim \text{Bin}(n, p) \\ X \sim \text{Poi}(\lambda) \\ X \sim \text{Exp}(\lambda) \\ X \sim \text{Unif}(a, b) \\ X \sim \text{N}(\mu, \sigma^2)

A random variable $X$ can have different types of supports. 

1. **Categorical**: The support has different categories, but there is no way of comparing $\geq$ or $\leq$ between two categories
- e.g. supp($X$) = {red, green, blue}
2. **Ordinal**: The support has different categories and there is a way of comparing $\geq$ or $\leq$ between two categories, but cannot quantify the difference between them
- e.g. supp($X$) = {low, medium, high}, supp($X$) = {good, okay, bad}
3. **Discrete**: The support is a discrete collection of objects where we can compare $\geq$ or $\leq$ between two categories and quantify the difference bewtween them
- e.g. supp($X$) = {0, 1}, supp($X$) = {0, 1, 2, ...}
4. **Continuous**: The support is a continuum
- e.g. supp($X$) = $\mathbb{R}$, supp($X$) = $\R^d$

### Example: Categorical Random Variables

Let $X$ be a random variable which represents the color of a randomly chosen car you see on the road. Then,

$$ \text{supp}(X) = \text{\{red, green, blue\}} $$

How can you encode this in a computer program?

e.g. One Hot Encoding

$$
X = 
\begin{cases} 
      (1, 0, 0)^T & x=\text{red} \\
      (0, 1, 0)^T & x=\text{green} \\
      (0, 0, 1)^T & x=\text{blue} 
\end{cases}
$$

Dummy Variable Encoding

$$
X = 
\begin{cases}
      (0, 0)^T & x=\text{red} \\
      (1, 0)^T & x=\text{green} \\
      (0, 1)^T & x=\text{blue}
\end{cases}
$$

#### Properties of Random Variables

**Probability Mas Function (PMF)**
- the pmf of a discrete RV $X$ is a function $f_X$ that gives the probability that X takes on a certain value
e.g.
$$
p_X = 
\begin{cases}
    \frac{1}{2} & x=0 \\
    \frac{1}{2} & x=1
\end{cases}
$$

**Probability Density Function (PDF)**
- the pdf of a continuous RV $X$ is a function $f_X$ that gives the probability that $X$ is in a particular interval
$$\mathbb{P}(a \leq X \leq b) = \int_{b}^{a} f_X dx

**Cumulative Distribution Function**

Intuitively, the cumulative distribution function (CDF) of a random variable $X$ measures the probability that X is less than or equal to a certain value.

For a random variable $X$ with PDF $f_x(x)$ the CDF $F_x(x)$ is given by
$$
F_x(x)  = \mathbb{P}(X \leq x) \tag{formula for CDF of continuous RV}
$$

**Expected value**

For a random variable $X$ with PMF $P_x$ or with PDF $f_x$, the expected value of $X$ is

$$
E(X)  = \sum_{k \in supp(X)} kP_x(k) \tag{formula for PMF}
$$
$$
E(X)  = \int_{supp(X)}x * f_X \tag{formula for PDF}
$$

In [2]:
X = stats.poisson(10)
EX = X.expect()
EX

10.000000000000023

**Variance**

For a random variable $X$ with expected value $E(X)$ and second moment $E(X^2)$, the variance of $X$ is


$$
var(X)  = E((X - E(X))^2) = E(X^2) - E(X)^2 \tag{formula for variance}
$$

In [3]:
EX2 = X.moment(2)
VarX = X.var()
VarX

10.0

In [4]:
EX2 - EX**2 # very close due to rounding errors

9.999999999999545

#### Examples of Probability Distributions

---

§1. Bernoulli distribution

A random variable $X \sim Ber(p)$ follows a Bernoulli distribution with parameter $p$

* The support is
$$
supp(X) = \{0, 1\}
$$
* The PMF is 
$$
P_x(x) = p^x(1-p)^{1-x}
$$
* The expected value is
$$
\mathbb E(X) = p
$$
* The variance is
$$
var(X) = p(1-p)
$$

In python, we can generate $10$ random samples from a Bernoulli distribution as follows:

In [5]:
X = stats.bernoulli(0.5)
X.rvs(10)

array([0, 0, 1, 1, 0, 1, 0, 1, 1, 1])

**Binomial from Bernoulli**

$$X \sim \text{Bin}(n, p)$$

$$f_X = {n\choose k} p^x(1-p)^{n-x}$$

$$X = \sum^N Y_i$$

$$Y_i \sim \text{be}(p)$$

---

§2. Discrete Uniform distribution

A random variable $X \sim Unif \{a, b\}$ follows a _discrete uniform_ distribution with parameter(s) a and b

* The support is
$$
supp(X) = [a. b]
$$
* The PMF is 
$$
P_x(x) =
\begin{cases}
    \frac{1}{b-a} & x \in supp(X) \\
    0 & \text{else}
\end{cases}
$$
* The expected value is
$$
\mathbb E(X) = \frac{b+a}{2}
$$
* The variance is
$$
var(X) = \frac{(b-a)^2}{12}
$$

We can generate $10$ random samples from a discrete uniform distribution as follows:

In [6]:
X = stats.randint(0, 10)
X.rvs(10)

array([0, 2, 5, 1, 0, 9, 2, 8, 1, 9])

---

§3. Poisson Distribution

A random variable $X \sim Poi(\lambda)$ follows a _Poisson_ distribution with parameter(s) $\lambda$

* The support is
$$
supp(X) = \{1, 2, ...\}
$$
* The PMF is 
$$
P_x(x) = \frac{e^{-\lambda} * \lambda^x}{x!}
$$
* The expected value is
$$
\mathbb E(X) = \lambda
$$
* The variance is
$$
Var(X) = \lambda
$$

We can generate $10$ random samples from a Poisson distribution as follows:

In [7]:
X = stats.poisson(20)
X.rvs(10)

array([25, 15, 29, 16, 19, 20, 18, 25, 21, 19])

---

§4. Exponential distribution

A random variable $X \sim Exp(\lambda)$ follows an _Exponential_ distribution with parameter(s) $\lambda$

* The support is
$$
supp(X) = (0, \infty)
$$
* The PDF is 
$$
fx(x) = \lambda e^{-\lambda x}, x \geq 0
$$
* The expected value is
$$
\mathbb E(X) = \frac{1}{\lambda}
$$
* The variance is
$$
Var(X) = \frac{1}{\lambda^2}
$$

We can generate $10$ random samples from an Exponential distribution as follows:

In [8]:
X = stats.expon(1)
X.rvs(10)

array([2.1237913 , 2.06533577, 1.03504198, 1.17793445, 1.68394137,
       1.5347119 , 1.15300737, 1.35254903, 3.51639745, 1.36980104])

---

§5. Normal Distribution

A random variable $X \sim N(\mu, \sigma^2)$ follows a Normal distribution with parameter(s) $\mu$, $\sigma$

* The support is
$$
supp(X) = \R
$$
* The PDF is 
$$
fx(x) = \frac{1}{\sqrt{2\pi \sigma^2}}e^{\frac{(x-\mu)^2}{2}}
$$
* The expected value is
$$
\mathbb E(X) = \mu
$$
* The variance is
$$
Var(X) = \sigma^2
$$

We can generate $10$ random samples from a Normal distribution as follows:

In [9]:
X = stats.norm(0, 1)
X.rvs(10)

array([-0.4262134 ,  2.19481731,  0.54297033,  0.82110068, -0.81057187,
        0.06085597, -0.56030807, -0.7446777 ,  1.03452343, -0.46265545])

---

§6. Chi-squared Distribution

A random variable $X \sim \chi^2(k)$ follows a Chi-squared distribution with parameter(s) k

* The support is
$$
supp(X) = (0, \infty)
$$
* $X \sim \chi^2(k)$ is obtained using $k$ iid copies of a standard normal random variable $Z_1, Z_2, \dots, Z_k \sim N(0, 1)$ as follows:
$$
X = \sum^N Z_i^2
$$
* The expected value is
$$
\mathbb E(X) = k
$$
* The variance is
$$
Var(X) = 2k
$$

We can generate $10$ random samples from a Chi-squared distribution as follows:

In [10]:
X = stats.chi2(10)
X.rvs(10)

array([ 2.45168102, 13.44532802, 10.9597844 ,  9.21968169, 15.54243462,
        5.81694638,  6.05304271, 10.42750191, 23.75284879,  4.88891727])

---

§7. Student's t Distribution

A random variable $X \sim t(k)$ follows a Student's $t$ distribution with parameter(s) ... 

* The support is
$$
supp(X) = (-\infty, \infty)
$$

* Given $Z \sim N(0,1)$ and $Y \sim \chi^2(k)$ with $Z \perp Y$, a Student's $t$ random variable $X$ is obtained as follows:
$$
X = \frac{Z}{\sqrt{\frac{Y}{k}}}
$$


We can generate $10$ random samples from a Student's $t$ distribution as follows:

In [11]:
X = stats.t(40)
X.rvs(10)

array([ 0.53422456,  0.9872681 , -1.16500969,  1.65938943, -0.30137908,
       -1.71798815, -1.25594503,  0.00507993,  0.1466212 , -0.21770989])

---

§8. $F$ Distribution

A random variable $X \sim F(k_1, k_2)$ follows an $F$ distribution with parameter(s) ... 

* The support is
$$
supp(X) =(0, \infty)
$$

* Given $Y \sim \chi^2(k_1)$ and $Z \sim \chi^2(k_2)$ with $Y \perp Z$, an $F$ random variable $X$ is obtained as follows:
$$
X = \frac{Y/k_1}{Z/k_2}
$$

We can generate $10$ random samples from a Normal distribution as follows:

In [12]:
X = stats.f(3, 2)
X.rvs(10)

array([ 8.52257287,  0.09448246,  0.7643795 ,  1.18561893,  0.75779279,
        0.4107955 ,  4.2285065 ,  0.38202945,  3.57939863, 38.83843883])

---

Suppose $X_1, X_2, \dots, X_n$ are $n$ iid samples from a distribution with mean $E(X) = M$ and variance $var(X) = V$.

Let $$\bar{X} = \frac{1}{n} \sum_{i=1}^n X_i$$ be the sample mean and $$S^2 = \frac{1}{n-1} \sum_{i=1}^n (X_i - \bar{X})^2$$ be the sample variance.

**Law of large Numbers**

In english, the law of large numbers says that as the number of observations increases, the average of the sample mean gets closer to the expected value.

$$
n \rightarrow \infty, \frac{1}{n}\sum^{n} x_i \rightarrow \mathbb{E}(X)
$$


**Central Limit Theorem**

In english, the central limit theorem says that as the number of observations increases, the distribution of the observed values gets closer and closer to the normal distribution.

$$
\frac{\bar{X} - \mathbb{E}(X)}{\sqrt{Var(X)}} \rightarrow N(0, 1) \text{ as } n \rightarrow \infty
$$

---
---

## Thu, Apr 11th

#### Quantile
Given a random variable $X \sim D$ and a number $\alpha \in (0,1)$, the $\alpha$-quantile of X is the value $q_\alpha$ such that

$$ 
\mathbb{P}(X \leq q_\alpha) = \alpha
$$

In terms of the CDF, this is

$$
F_X(q_\alpha) = \alpha
$$

In other words, $q_\alpha$ is the value such that the probability that $X$ is less than or equal to $q_\alpha$ is exactly $\alpha$.

#### Empirical CDF
Given samples $X_1, X_2,...,X_n$ from a random variable $X$m the empirical CDF is given by 
$$
\hat{F}_h(x) = \frac{1}{n} \sum_{i=1}^{n} I(X_i \leq x)
$$
where $I(X_i \leq x)$ is the indicator function
$$
I(X_i \leq x) = \begin{cases} 1 & \text{ if } X_i \leq x \\ 0 & \text{ else} \end{cases}
$$
Using the empirical CDF, $\hat{F}_n(x)$, we can compute the **empirical quantile** of $X_1,X_2,...,X_n$, which is 
$$
\hat{q}_\alpha = (100 \times \alpha)\% \text{ of } X_1,...,X_n
$$

#### Statistic

Suppose $X_n$ is sampled iid from a distribution $D(\theta)$ where $\theta$ is a parameter.

Then, intuitively, a statistic $\hat\theta \equiv \hat\theta(X_n)$ is a best guess for the parameter $\theta$.


#### Sampling Distribution

Since $X_n$ are all random variables, the statistic $\hat\theta$ is also a random variable.

In words, the sampling distribution of $\hat\theta$ is the distribution of $\hat\theta$ when $X_1,X_2,...,X_n$ are drawn from $D(\theta)$.

#### Intuition behind Sampling Distributions

If we call the process of sampling $X_n$ from $D(\theta)$ as a "**random experiment**", then let

* $\hat\theta^{(1)}, \hat\theta^{(1)}, \dots, \hat\theta^{(N)}$ be the statistics obtained from each of $N$ random experiments.

Then, the sampling distribution of $\hat\theta$ roughly is

$$ \hat{\theta} \sim N(\theta, \frac{\sigma^2}{n}) $$

---

#### Confidence Interval

The **$100 \times (1-\alpha)\%$ confidence interval** for a parameter $\theta$ is an interval $[l_\alpha, u_\alpha]$ such that:

$$
\mathbb{P}(l_\alpha \leq \theta \leq u_\alpha) = 1 - \alpha
$$

we denote this as $CI(\theta) = [l_\alpha, u_\alpha]$.

For a statistic $\hat\theta$ with standard error $SE(\hat\theta)$ the general formula for the $100 \times (1-\alpha)\%$ confidence interval is given by


$$
CI(\theta, \alpha) = [\hat{\theta} - q_{1-\alpha/2} \times SE(\hat\theta), \hat{\theta} + q_{1-\alpha/2} \times SE(\hat\theta)]
$$

where $z_{\alpha/2}$ is the $(1-\alpha/2)$ quantile of the standard normal distribution.

#### Interpretation of Confidence Intervals

If we call the process of sampling $X_n$ from $D(\theta)$ as a "**random experiment**" where $\theta^*$ is the true, unknown population parameter.  

Let

$$
[l_\alpha^{(1)}, u_\alpha^{(1)}], [l_\alpha^{(2)}, u_\alpha^{(2)}], \dots, [l_\alpha^{(N)}, u_\alpha^{(N)}]
$$

be the $100 \times (1-\alpha)\%$ confidence intervals obtained from each of $N$ random experiments.




Then, the guarantee provided by the construction of the confidence interval is that 

$$ 100 \times (1 - \alpha)\% \text{ of the time the true parameter } \theta \text{ will lie in these intervals.} $$

The proportion of times that the true parameter $\theta$ lies in the interval $[l_\alpha, u_\alpha]$ is called the **coverage probability** of the interval.

---

#### Examples of Confidence Intervals (from Math 183 or equivalent)

---

§1. One sample Proportion

| Description | Answer |
|:---|:---|
| Assumption | $X_n \sim Be(\theta)$ |
| Population parameter | $\theta = \text{true proportion}$ |
| Statistic | $\hat\theta = \frac{1}{n} \sum_{i=1}^{n} X_i$ |
| Standard Error | $SE(\hat\theta) = \sqrt{\frac{\hat{\theta}(1-\hat{\theta})}{n}}$ |
| Sampling distribution | $D_{\hat\theta} \sim \frac{1}{n} Bin(n, \theta)$ |

The **99\% confidence interval** for $\theta$ is given by

$$
CI(\theta, \alpha) = [\hat{\theta} - z_{0.005}\sqrt{\frac{\hat{\theta}(1-\hat{\theta})}{n}}, \hat{\theta} + z_{0.005}\sqrt{\frac{\hat{\theta}(1-\hat{\theta})}{n}}]
$$

In [13]:
true_theta = 0.75
n = 1000
alpha = 0.01
X = stats.bernoulli(true_theta)
sample = X.rvs(n)

In [14]:
theta_hat = sample.mean()
SE = np.sqrt(theta_hat * (1 - theta_hat) / n)
Z = stats.norm(0, 1)
z = Z.ppf(1 - alpha/2)

In [15]:
ci = [theta_hat - z*SE, theta_hat + z*SE] # 95% CI

In [16]:
print(theta_hat, SE, "\n", ci)

0.749 0.013711272734505722 
 [0.713682101901509, 0.784317898098491]


---

§2. Difference of two proportions

| Description | Answer |
|:---|:---|
| Assumption | $X_n \sim Be(\theta_X)$  and $Y_m \sim Be(\theta_Y)$|
| Population parameter | $\theta = \theta_X - \theta_Y$ |
| Statistic | $\hat\theta = \hat{\theta}_X - \hat{\theta}_Y$ |
| Standard Error | $SE(\hat\theta) = \sqrt{\frac{\hat{\theta}_X(1 - \hat{\theta}_X)}{n} + \frac{\hat{\theta}_Y(1 - \hat{\theta}_Y)}{m}}$ |
| Sampling distribution | $D_{\hat\theta} \sim \frac{1}{n + m} Bin(n+m, \theta_X - \theta_Y)$ |

The **97\% confidence interval** for $\theta$ is given by

$$
CI(\theta, \alpha) = [\hat{\theta} - z_{0.015}SE, \hat{\theta} + z_{0.015}SE]
$$

In [17]:
X = stats.bernoulli(0.6)
Y = stats.bernoulli(0.4)
n = 600
m = 400
alpha = 0.03
sample_x = X.rvs(n)
sample_y = Y.rvs(m)

In [18]:
theta_x = sample_x.mean()
theta_y = sample_y.mean()
theta_hat = theta_x - theta_y
SE = np.sqrt(
    (theta_x * (1 - theta_x) / n) + (theta_y * (1 - theta_y) / m)
)
z = Z.ppf(1 - alpha/2)

In [19]:
ci = [theta_hat - z*SE, theta_hat + z*SE]

In [20]:
print(theta_hat, SE, "\n", ci)

0.2025 0.03163306879938566 
 [0.1338533817849828, 0.27114661821501723]


---