# Week 1 Summary
> NAME: $\color{red}{\text{Lucien Chen}}$
> 
> PID: $\color{red}{\text{A17004542}}$
>
> 
---

I certify that the following write-up is my own work, and have abided by the UCSD Academic Integrity Guidelines.

- [x] Yes
- [ ] No

---

## Key Takeaways from Week 1

#### Thursday

Markdown is a useful tool for scientific communication. It allows us to write beautiful math equations and do all sorts of other text formatting within the context of a Jupyter notebook and as a standalone file. We also covered the basics of Python such as datatypes, control flow, loops, etc. Additionally, we also covered linear algebra operations in Python using numpy. Some of which included vector addition, matrix multiplication, and eigenvalues/vectors.


---

## Thu, Apr 4th

### Basics of markdown

**Bullet Lists and Numbered Lists**

This is a bullet list:

* Item 1
    - Subitem 1
        - Subsubitem 1
            - Subsubsubitem 1
                - Subsubsubsubitem 1
                    - Subsubsubsubsubitem 1
    - Subitem 2
* Item 2
* Item 3

This is a numbered list:
1. Item 1
    1. Subitem 1
        1. Subsubitem 1
        1. Subsubitem 2
2. Item 2
3. Item 3

**Math**

$\LaTeX$

This is an in-line math equation $\alpha x^2 + \beta x + c = 0$ (quadratic)

Below is a stand alone math equation

$$ e^x = \sum_{n=0}^\infty \frac{x^n}{n!}  $$

$$
\begin{aligned}
\bar{X} = \frac{1}{n} \sum_{i=1}^n x_i
\end{aligned}
$$

**Boxed & Colored Equations**

This is the expression for sample mean
$$
\boxed{
\color{skyblue}{\frac{1}{n} \sum_{i=1}^n X_i}
}
$$

**Math Macros**

$$
\newcommand{\newsum}[2]{\sum_{i=#1}^{#2}}

\newsum{0}{n} x_i
$$

$$
\newcommand{\Xn}{X_1, X_2, \cdots, X_n}
\Xn \text{ is sampled iid from $H_0$}
$$

---

**Data Types**

We have int, float, string and bool.

In [1]:
int(1.1)

1

In [2]:
float(1)

1.0

In [3]:
str(0) + "abc" * 3

'0abcabcabc'

In [4]:
bool(0)

False

In [5]:
bool(1)

True

**Arithmetic Operations (+, -, \*, /, %, //)**

In [6]:
3 // 2 # returns the remainder after division

1

In [7]:
13 * 2

26

In [8]:
12/2

6.0

In [9]:
1 + 1

2

In [10]:
100 - 90

10

In [11]:
4 ** 4 # exponentiation

256

**Data Structures (Lists, Tuples, Sets, Dicts)**

In [12]:
lst = [1, 2, 3]
type(lst)

list

In [13]:
lst[0]

1

In [14]:
tup = 1, 2, 3
type(tup)

tuple

In [15]:
tup[2]

3

In [16]:
dct = {"name": "Lucien"}
dct["name"] # accessing a dict using key-value

'Lucien'

In [17]:
keys = ["a", "b", "c"]
values = [1, 2, 3]
another_dict = dict(zip(keys, values))
another_dict

{'a': 1, 'b': 2, 'c': 3}

In [18]:
a = {1, 2, 3}
b = {4, 5, 6}
a.issubset(b)

False

**Conditionals, Loops**

In [19]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [20]:
if 10 > 5:
    print("5 is not greater than 10")

5 is not greater than 10


In [21]:
n = 0
while n < 15:
    print("*" * n)
    n += 1


*
**
***
****
*****
******
*******
********
*********
**********
***********
************
*************
**************


**Functions**

In [22]:
def fibonacci(n):
    return 0 if n == 0 else 1 if n == 1 else n + fibonacci(n-1)

In [23]:
fibonacci(3)

6

In [24]:
fib = lambda n: 0 if n == 0 else 1 if n == 1 else n + fib(n-1) # anonymous/lambda function
fib(3)

6

**Vectors**

In [25]:
import numpy as np

In [26]:
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])
v

array([1, 2, 3])

In [27]:
w

array([4, 5, 6])

When you add two vectors ...

In [28]:
v + w

array([5, 7, 9])

When you multiply a vector by a scalar you get a new vector where each element is the element-wise sum of the two arrays:

$$
\begin{align}
\vec{Z} = \vec{V} + \vec{W}
\\
z_i = v_i + w_i
\end{align}
$$

In [29]:
10 * v

array([10, 20, 30])

You can "multiply" two vectors in two different ways:

1. dot product:
$$
u^Tv = \sum_{i=1}^n u_iv_i
$$
2. cross product:
$$
A \times B = \|A\| \|B\| sin(\theta)n
$$

In Python:

In [30]:
v.T.dot(w)

32

In [31]:
np.cross(v, w)

array([-3,  6, -3])

**Matrices**

Intuitively, a matrix is n vectors of size m (m x n)

In [32]:
mat = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [33]:
mat

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

When a matrix acts on a vector, you get ...

In [34]:
# Creating vectors and matrices
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculating the product
product = matrix * vector
product

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [35]:
matrix @ vector

array([14, 32, 50])

In [36]:
matrix @ matrix

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

**Basic linear algebra operations:**
1. Norm: the length of a measure
$$
\|X\| = \sqrt{\sum_{i=1}^n x_i^2}
$$
2. Dot product: the product of the magnitude of two vectors:
a^Tb = \sum_{i=1}^n a_ib_i
4. Matrix transpose: the flipped form of a matrix
$$
A = \begin{bmatrix}
1 & 2 & 3 \\ 4 & 5 & 6
\end{bmatrix}
$$
$$
A^T = \begin{bmatrix}
1 & 4 \\ 2 & 5 \\ 3 & 6
\end{bmatrix}
$$
4. Matrix inverse: another matrix such that

$$ A * A^{-1} = I $$

where $I$ is the identity matrix

In [37]:
A = np.matrix([[1, 2], [3, 4]])
A

matrix([[1, 2],
        [3, 4]])

In [38]:
np.linalg.norm(A) # norm

5.477225575051661

In [39]:
A * A # dot product

matrix([[ 7, 10],
        [15, 22]])

In [40]:
A.T # transpose

matrix([[1, 3],
        [2, 4]])

In [41]:
A_inverse = np.linalg.inv(A) # inverse
A_inverse

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [42]:
A * A_inverse # the bottom left "nonzero" is due to rounding errors

matrix([[1.00000000e+00, 1.11022302e-16],
        [0.00000000e+00, 1.00000000e+00]])

**Slightly more advanced linear algebra operations**

If we're given a system of equations, for example, 

$$
\begin{align*}
2x + 3y &= 5 \\
4x + 5y &= 6
\end{align*}
$$

We can represent it in the matrix-vector form as ...

$$
\begin{pmatrix}
2 & 3 \\ 4 & 5
\end{pmatrix}
\begin{pmatrix}
x \\ y
\end{pmatrix}
= 
\begin{pmatrix}
5 \\ 6
\end{pmatrix}

The solution for the unknown variables, $(x, y)$ is given by ...

$$ \begin{pmatrix} x \\ y \end{pmatrix} = \begin{pmatrix} -\frac{7}{2} \\ 4 \end{pmatrix} $$

In code, we can do this as follows: ...

In [43]:
# Solving a system of linear equations
A = np.array([[2, 3], [4, 5]])
b = np.array([5, 6])
solution = np.linalg.solve(A, b)
solution # equivalent to the solution above

array([-3.5,  4. ])

---

**Eigenvalues and eigenvectors**

Given an $n \times n$ matrix $A$, the eigenvalue of $A$ is the scalar $\lambda$ such that $\exists$ a $v$ s.t. $Av = \lambda v$

The eigenvector of $A$ is the vector $v$ such that $\exists$ a $\lambda$ s.t. $Av = \lambda v$

Intuitively, the eigenvector of a matrix describes vector(s) in which multiplying by A results in another vector with the same or opposite direction, that is the resulting vector is parallel.

In code, we can compute the eigenvalues and eigenvectors of a matrix as follows:

In [44]:
a = np.random.randn(2, 2)
A = a @ a.T
eigvals, eigvecs = np.linalg.eig(A)

We can verify that the eigenvalues and eigenvectors are correct by running the following code and ensuring that the output matches the expected values:


In [45]:
eigvals

array([0.18041685, 1.43154845])

In [46]:
lambda1 = max(eigvals) # Largest eigenvalue
v1 = eigvecs[:, np.argmax(eigvals)] # Corresponding eigenvector


# Expected value of Av
expected_value = lambda1 * v1

# Actual value of Av
Av = A @ v1

# Check if the expected value and actual value are equal
np.allclose(expected_value, Av)

True

As we can see from above, our mathematical definition of eigenvalues and eigenvectors are correct. In the code example, we see that $Av = \lambda v$ when $\lambda$ is one of the eigenvalues and $v$ is the corresponding eigenvector.